export const REQUEST_LATEST_DATA = "REQUEST_LATEST_DATA";
export const SHOW_LATEST_DATA = "SHOW_LATEST_DATA";
export const FAILED_GET_DATA = "FAILED_GET_DATA";
export const SUCCES_GET_DATA = "SUCCES_GET_DATA";
